### PR TITLE
Lock coffee-script-source

### PR DESCRIPTION
**Pull request by pathawks**
**This should be only temporary**

v1.12 was causing Jekyll tests to fail
https://github.com/jekyll/jekyll/pull/5661#issuecomment-267381479

### CODE REVIEW

**Comment by pathawks** [comment]
_Ugh_ Why are we testing against Ruby 1.9?

**Comment by parkr** [comment]
@jekyllbot: merge +bug

**Comment by parkr** [comment]
@pathawks is this still necessary?

**Pull request merged**
